### ISSUE TITLE
How can i change font size on 128x64 graphics LCD with Html and Js code

### ISSUE THREAD

**Issue by interstellarelectric** [visrealm/vrEmuLcd#4]
Hi, This is a wonderful Library I want to use for my web project, I wonder how can i change font size on 128x64 graphics LCD with Html and Js code

**Comment by visrealm** [comment]
Hi. Thanks.
The font size for the 128x64 can't be changed. It's exactly as per the [12864B datasheet](https://www.exploreembedded.com/wiki/images/7/77/QC12864B.pdf)

You can however put the LCD into graphics mode and render whatever you like to it. Again, following the datasheet. I created the library to emulate my various hardware projects, so have only ever needed to support the same interface as the real device.

What font size are you wanting?

**Comment by interstellarelectric** [comment]
I'm not sure the exact font size, but sure I will try the graphics mode, Thanks!

**Comment by visrealm** [comment]
Closed as will not fix
